(() => {
  'use strict';

  // This deliberately remains a transparent rules demo, rather than presenting
  // keyword matching as clinical AI or a substitute for a trained professional.
  const STORAGE_KEY = 'mindcare-demo-v2';
  const moodData = {
    Difficult: { value: 20, title: 'A hard moment', note: 'You do not have to carry this alone.', counselor: { score: 85, status: 'Review now', tone: 'review', signal: 'A lower check-in may benefit from a timely, human-led review.', preview: '“Today feels especially difficult. I could use some support.”', trend: 'M2 18 C30 18,38 48,68 42 S112 20,142 37 S185 61,218 57' } },
    Low: { value: 40, title: 'A gentle day', note: 'Small, caring steps are enough today.', counselor: { score: 72, status: 'Check in', tone: 'review', signal: 'A gentle follow-up may be helpful today.', preview: '“I’m feeling low today and would appreciate a little support.”', trend: 'M2 28 C28 27,37 43,67 39 S111 25,142 37 S185 48,218 42' } },
    Okay: { value: 62, title: 'Steady today', note: 'It’s okay to be exactly where you are.', counselor: { score: 62, status: 'Steady', tone: 'stable', signal: 'Monitoring signal, not a clinical diagnosis.', preview: '“I’m feeling okay today. I’m taking things one moment at a time.”', trend: 'M2 45 C25 40,33 58,55 45 S86 13,107 27 S139 48,157 32 S190 25,218 13' } },
    Good: { value: 78, title: 'A positive moment', note: 'Notice what is helping you feel this way.', counselor: { score: 40, status: 'Improving', tone: 'stable', signal: 'A positive check-in suggests steadier support needs.', preview: '“I’m feeling good today. A few things have been helping.”', trend: 'M2 52 C28 54,39 40,69 42 S111 28,143 32 S187 18,218 15' } },
    Bright: { value: 92, title: 'Feeling bright', note: 'Let this good moment be yours to enjoy.', counselor: { score: 18, status: 'Bright', tone: 'stable', signal: 'A positive check-in suggests lower current support needs.', preview: '“I’m feeling bright today and wanted to share that.”', trend: 'M2 58 C28 55,40 45,68 40 S110 29,142 25 S182 13,218 8' } }
  };
  const translations = {
    English: { space: 'My space', counselor: 'Counselor view', checkin: "TODAY'S CHECK-IN", howFeel: 'How are you feeling?', selected: 'Selected', difficult: 'Difficult', low: 'Low', okay: 'Okay', good: 'Good', bright: 'Bright' },
    'हिन्दी': { space: 'मेरा स्थान', counselor: 'काउंसलर दृश्य', checkin: 'आज का चेक-इन', howFeel: 'आप कैसा महसूस कर रहे हैं?', selected: 'चुना गया', difficult: 'कठिन', low: 'कम', okay: 'ठीक', good: 'अच्छा', bright: 'बहुत अच्छा' },
    'தமிழ்': { space: 'என் இடம்', counselor: 'ஆலோசகர் பார்வை', checkin: 'இன்றைய பதிவு', howFeel: 'நீங்கள் எப்படி உணர்கிறீர்கள்?', selected: 'தேர்ந்தெடுத்தது', difficult: 'கடினம்', low: 'குறைவு', okay: 'சரி', good: 'நன்று', bright: 'மிக நன்று' },
    'తెలుగు': { space: 'నా స్థలం', counselor: 'కౌన్సిలర్ వీక్షణ', checkin: 'నేటి చెక్-ఇన్', howFeel: 'మీరు ఎలా ఉన్నారు?', selected: 'ఎంచుకున్నది', difficult: 'కష్టం', low: 'తక్కువ', okay: 'సరే', good: 'మంచిది', bright: 'చాలా బాగుంది' },
    'ಕನ್ನಡ': { space: 'ನನ್ನ ಸ್ಥಳ', counselor: 'ಸಲಹೆಗಾರರ ನೋಟ', checkin: 'ಇಂದಿನ ಚೆಕ್-ಇನ್', howFeel: 'ನೀವು ಹೇಗೆ ಭಾವಿಸುತ್ತಿದ್ದೀರಿ?', selected: 'ಆಯ್ಕೆಮಾಡಿದ್ದು', difficult: 'ಕಷ್ಟ', low: 'ಕಡಿಮೆ', okay: 'ಸರಿ', good: 'ಒಳ್ಳೆಯದು', bright: 'ಬಹಳ ಚೆನ್ನಾಗಿದೆ' },
    'മലയാളം': { space: 'എന്റെ സ്ഥലം', counselor: 'കൗൺസിലർ കാഴ്ച', checkin: 'ഇന്നത്തെ ചെക്ക്-ഇൻ', howFeel: 'നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു?', selected: 'തിരഞ്ഞെടുത്തത്', difficult: 'പ്രയാസം', low: 'കുറവ്', okay: 'ശരി', good: 'നല്ലത്', bright: 'മികച്ചത്' },
    'বাংলা': { space: 'আমার স্থান', counselor: 'কাউন্সেলর ভিউ', checkin: 'আজকের চেক-ইন', howFeel: 'আপনি কেমন অনুভব করছেন?', selected: 'নির্বাচিত', difficult: 'কঠিন', low: 'কম', okay: 'ঠিক আছে', good: 'ভালো', bright: 'দারুণ' },
    'मराठी': { space: 'माझी जागा', counselor: 'समुपदेशक दृश्य', checkin: 'आजची नोंद', howFeel: 'तुम्हाला कसे वाटत आहे?', selected: 'निवडलेले', difficult: 'कठीण', low: 'कमी', okay: 'ठीक', good: 'चांगले', bright: 'उत्कृष्ट' },
    'ગુજરાતી': { space: 'મારી જગ્યા', counselor: 'કાઉન્સેલર દૃશ્ય', checkin: 'આજનું ચેક-ઇન', howFeel: 'તમે કેવું અનુભવો છો?', selected: 'પસંદ કરેલ', difficult: 'મુશ્કેલ', low: 'ઓછું', okay: 'ઠીક', good: 'સારું', bright: 'ખૂબ સારું' },
    'ਪੰਜਾਬੀ': { space: 'ਮੇਰੀ ਥਾਂ', counselor: 'ਕੌਂਸਲਰ ਦ੍ਰਿਸ਼', checkin: 'ਅੱਜ ਦਾ ਚੈਕ-ਇਨ', howFeel: 'ਤੁਸੀਂ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ?', selected: 'ਚੁਣਿਆ ਗਿਆ', difficult: 'ਮੁਸ਼ਕਲ', low: 'ਘੱਟ', okay: 'ਠੀਕ', good: 'ਚੰਗਾ', bright: 'ਬਹੁਤ ਵਧੀਆ' }
  };
  const pageCopy = { English: { date: 'TUESDAY, 25 AUGUST', welcomeTitle: 'A quiet space for <em>you.</em>', welcome: 'Welcome back, Akshavi. We can take this one moment at a time.' }, 'தமிழ்': { date: 'செவ்வாய், 25 ஆகஸ்ட்', welcomeTitle: 'உங்களுக்கான அமைதியான <em>இடம்.</em>', welcome: 'மீண்டும் வரவேற்கிறோம், அக்ஷவி. ஒரு நேரத்தில் ஒரு தருணத்தை எடுத்துக்கொள்ளலாம்.' } };
  const seedPeople = () => [
    { id: 'akshavi', initials: 'AK', name: 'Akshavi', queueMeta: 'Investigation · Checked in today', detailMeta: 'Investigation stage · Weekly check-in', ...moodData.Okay.counselor },
    { id: 'yaswant', initials: 'YM', name: 'Yaswant', queueMeta: 'Trial · Missed two check-ins', detailMeta: 'Trial stage · Follow-up due', score: 74, status: 'Review', tone: 'review', signal: 'A follow-up may be helpful after missed check-ins.', preview: '“I have missed a couple of check-ins this week.”', trend: 'M2 20 C28 25,42 54,66 48 S108 24,143 39 S184 47,218 33' },
    { id: 'bala', initials: 'BS', name: 'Bala', queueMeta: 'Compensation · Checked in yesterday', detailMeta: 'Compensation stage · Weekly check-in', score: 55, status: 'Watch', tone: 'watch', signal: 'Continue to observe recent check-in patterns.', preview: '“Yesterday felt manageable, but I’m still adjusting.”', trend: 'M2 42 C29 31,39 57,68 45 S111 36,143 43 S184 31,218 29' },
    { id: 'armaan', initials: 'AP', name: 'Armaan', queueMeta: 'Investigation · Checked in 3 days ago', detailMeta: 'Investigation stage · Follow-up due', score: 70, status: 'Review', tone: 'review', signal: 'A gentle follow-up is suggested after time away.', preview: '“It has been a few days since my last check-in.”', trend: 'M2 28 C30 34,40 57,68 49 S109 28,144 45 S184 52,218 37' }
  ];
  const byId = (id) => document.getElementById(id);
  const getStored = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } };
  const saved = getStored(); const people = Array.isArray(saved.people) ? saved.people : seedPeople();
  let selectedMoodName = saved.selectedMoodName || 'Okay'; let selectedPersonId = saved.selectedPersonId || 'akshavi'; let history = Array.isArray(saved.history) && saved.history.length ? saved.history : [55, 61, 57, 66, 62]; let timerId; let databaseHydrated = false;
  const stateSnapshot = () => ({ people, selectedMoodName, selectedPersonId, history });
  const save = () => {
    const state = stateSnapshot();
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { /* Storage may be unavailable in private browsing. */ }
    if (databaseHydrated && location.protocol.startsWith('http')) {
      window.fetch('/api/state', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(state) }).catch(() => { /* Local storage remains the offline fallback. */ });
    }
  };
  const t = (key) => (translations[byId('language').value] || translations.English)[key] || translations.English[key] || key;
  const copy = (key) => (pageCopy[byId('language').value] || pageCopy.English)[key] || pageCopy.English[key] || key;
  const currentPerson = () => people.find((person) => person.id === selectedPersonId) || people[0]; const akshavi = () => people.find((person) => person.id === 'akshavi');
  const applyLanguage = () => {
    const language = byId('language').value; document.documentElement.lang = { English: 'en', 'हिन्दी': 'hi', 'தமிழ்': 'ta', 'తెలుగు': 'te', 'ಕನ್ನಡ': 'kn', 'മലയാളം': 'ml', 'বাংলা': 'bn', 'मराठी': 'mr', 'ગુજરાતી': 'gu', 'ਪੰਜਾਬੀ': 'pa' }[language] || 'en';
    const page = pageCopy[language] || pageCopy.English; document.querySelectorAll('[data-i18n]').forEach((element) => { const key = element.dataset.i18n; element.textContent = Object.hasOwn(page, key) ? page[key] : t(key); }); document.querySelectorAll('[data-i18n-html]').forEach((element) => { element.innerHTML = copy(element.dataset.i18nHtml); });
    document.querySelectorAll('.moods button').forEach((button) => { const label = t(button.dataset.mood.toLowerCase()); button.querySelector('small').textContent = label; button.setAttribute('aria-label', label); }); byId('selectedMood').textContent = `${t('selected')}: ${t(selectedMoodName.toLowerCase())}`;
  };
  const stopTimer = (hideModal = true) => { if (timerId) window.clearInterval(timerId); timerId = undefined; if (hideModal) byId('modal').hidden = true; };
  const showModal = (title, text, kicker = 'MINDFUL MOMENT', actionLabel = 'I understand', html = false) => { stopTimer(false); byId('modalTitle').textContent = title; byId('modalText')[html ? 'innerHTML' : 'textContent'] = text; byId('modalKicker').textContent = kicker; byId('timerDisplay').hidden = true; const action = byId('modalAction'); action.hidden = false; action.textContent = actionLabel; action.setAttribute('data-close-modal', ''); action.onclick = null; byId('modal').hidden = false; };
  const startTimer = ({ title, text, kicker, seconds }) => { showModal(title, text, kicker, 'Stop timer'); const display = byId('timerDisplay'); const action = byId('modalAction'); let remaining = seconds; const render = () => { display.textContent = `${String(Math.floor(remaining / 60)).padStart(2, '0')}:${String(remaining % 60).padStart(2, '0')}`; }; display.hidden = false; render(); action.removeAttribute('data-close-modal'); action.onclick = () => stopTimer(); timerId = window.setInterval(() => { remaining -= 1; render(); if (remaining <= 0) { stopTimer(false); byId('modalTitle').textContent = 'Nice work.'; byId('modalText').textContent = 'You completed this gentle moment.'; action.textContent = 'Close'; action.setAttribute('data-close-modal', ''); } }, 1000); };
  const renderJourney = () => { const data = history.slice(-7); const minimum = Math.min(...data); const span = Math.max(...data) - minimum || 1; const points = data.map((value, index) => `${2 + (176 * index / Math.max(data.length - 1, 1))},${42 - ((value - minimum) / span) * 32}`).join(' L'); byId('journeyChartPath').setAttribute('d', `M${points}`); byId('journeyChartLabel').textContent = `Your recent wellness check-ins: ${data.join(', ')} out of 100.`; byId('weeklyCheckins').textContent = Math.min(history.length, 7); };
  const renderCounselorDetail = (person) => { byId('detailAvatar').textContent = person.initials; byId('detailName').textContent = person.name; byId('detailMeta').textContent = person.detailMeta; byId('detailStatus').textContent = person.status; byId('detailStatus').className = `status ${person.tone}`; byId('ddsValue').innerHTML = `${person.score} <small>/ 100</small>`; byId('ddsText').textContent = person.signal; byId('previewText').textContent = person.preview; document.querySelector('.preview span').textContent = person.id === 'akshavi' ? 'Today · Just now' : 'Today · 10:42 AM'; byId('counselorTrend').querySelector('path').setAttribute('d', person.trend); byId('counselorTrendLabel').textContent = `${person.name}’s recent wellness trend. Current support score: ${person.score} out of 100.`; };
  const renderCaseList = () => { const list = byId('caseList'); list.replaceChildren(); people.forEach((person) => { const row = document.createElement('button'); row.type = 'button'; row.className = `case-row${person.id === selectedPersonId ? ' active' : ''}`; row.setAttribute('aria-label', `View ${person.name}`); const avatar = document.createElement('span'); avatar.className = 'case-avatar'; avatar.textContent = person.initials; const info = document.createElement('span'); info.className = 'case-info'; const name = document.createElement('strong'); name.textContent = person.name; const meta = document.createElement('small'); meta.textContent = person.queueMeta; info.append(name, meta); const status = document.createElement('span'); status.className = `status ${person.tone}`; status.textContent = person.status; row.append(avatar, info, status); row.addEventListener('click', () => { selectedPersonId = person.id; save(); renderCaseList(); renderCounselorDetail(person); }); list.append(row); }); };
  const updateCounselorFromMood = (mood, message) => { const person = akshavi(); Object.assign(person, mood.counselor, { score: mood.value, detailMeta: `Investigation stage · ${mood.title} check-in`, queueMeta: 'Investigation · Checked in today', preview: message ? `“${message}”` : mood.counselor.preview }); selectedPersonId = 'akshavi'; renderCaseList(); renderCounselorDetail(person); save(); };
  const setMood = (name, message, record = true) => { const mood = moodData[name]; selectedMoodName = name; document.querySelectorAll('.moods button').forEach((button) => button.classList.toggle('selected', button.dataset.mood === name)); byId('selectedMood').textContent = `${t('selected')}: ${t(name.toLowerCase())}`; byId('checkinValue').textContent = `${mood.value}%`; byId('checkinFill').style.width = `${mood.value}%`; byId('moodNote').textContent = mood.note; byId('pulseTitle').textContent = mood.title; byId('pulseCopy').textContent = `Your check-in is ${name.toLowerCase()} today.`; byId('pulseNumber').textContent = mood.value; byId('pulseRing').style.setProperty('--progress', `${mood.value}%`); byId('pulseRing').setAttribute('aria-label', `Wellness indicator ${mood.value} out of 100`); if (record) { history.push(mood.value); history = history.slice(-14); } renderJourney(); updateCounselorFromMood(mood, message); save(); };
  const crisisPattern = /\b(kill myself|end my life|suicid(?:e|al)|self[- ]?harm|hurt myself|want to die|don't want to live|do not want to live|can't go on|cannot go on|in immediate danger|not safe|unsafe)\b/i;
  const moodFromMessage = (message) => { const text = message.toLowerCase(); if (/(\bnot (okay|ok|fine)\b|can't cope|cannot cope|falling apart|overwhelmed|panic(?:king)?|anxious|hopeless|terrified|scared|very sad|difficult)/.test(text)) return 'Difficult'; if (/(\blow\b|tired|need a (small )?pause|stressed|drained|down|exhausted|lonely|worried)/.test(text)) return 'Low'; if (/(bright|excited|joyful|amazing|great|wonderful)/.test(text)) return 'Bright'; if (/(\bgood\b|better|calm|grateful|happy|relieved)/.test(text)) return 'Good'; return 'Okay'; };
  const addMessage = (kind, text) => { const bubble = document.createElement('div'); bubble.className = `message ${kind}`; bubble.textContent = text; byId('messages').append(bubble); bubble.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); };
  const showSafetyFlow = () => { byId('safetyPanel').hidden = false; byId('safetyPanel').scrollIntoView({ behavior: 'smooth', block: 'nearest' }); };
  const openView = (view) => { const counselor = view === 'counselor'; byId('careView').hidden = counselor; byId('counselorView').hidden = !counselor; document.querySelectorAll('.nav-link').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); };
  const chooseRole = (role) => { byId('roleGate').hidden = true; byId('appShell').hidden = false; document.querySelector('[data-view="care"]').hidden = role === 'counselor'; document.querySelector('[data-view="counselor"]').hidden = role === 'patient'; openView(role === 'counselor' ? 'counselor' : 'care'); };

  document.querySelectorAll('[data-role]').forEach((button) => button.addEventListener('click', () => chooseRole(button.dataset.role)));
  document.querySelectorAll('.moods button').forEach((button) => button.addEventListener('click', () => setMood(button.dataset.mood)));
  byId('chatForm').addEventListener('submit', (event) => { event.preventDefault(); const input = byId('chatText'); const message = input.value.trim(); if (!message) return; addMessage('user', message); input.value = ''; if (crisisPattern.test(message)) { showSafetyFlow(); addMessage('crisis', 'I’m really glad you said something. Please use the immediate-support options now, and contact someone you trust nearby.'); return; } const mood = moodFromMessage(message); setMood(mood, message); addMessage('bot', 'Thank you for sharing. This rule-based demo has reflected your check-in in the support summary.'); });
  document.querySelectorAll('.suggestions button').forEach((button) => button.addEventListener('click', () => { byId('chatText').value = button.textContent; byId('chatText').focus(); }));
  byId('alertCounselorBtn').addEventListener('click', () => { const person = akshavi(); person.status = 'Review now'; person.tone = 'review'; person.score = Math.max(person.score, 90); person.signal = 'Safety support request shown. Human review is needed under local protocol.'; person.preview = '“I asked for immediate support.”'; selectedPersonId = 'akshavi'; save(); renderCaseList(); renderCounselorDetail(person); byId('alertCounselorBtn').textContent = 'Counselor alert requested'; byId('alertCounselorBtn').disabled = true; });
  document.querySelectorAll('.resource')[0].addEventListener('click', () => startTimer({ kicker: 'BOX BREATHING', title: 'Breathe with a steady rhythm', text: 'Breathe in for 4, hold for 4, breathe out for 4, then hold for 4. Repeat gently.', seconds: 120 })); document.querySelectorAll('.resource')[1].addEventListener('click', () => startTimer({ kicker: 'GROUNDING GUIDE', title: 'Use your five senses', text: 'Look around and slowly name the things you can see, feel, hear, smell, and taste.', seconds: 60 })); byId('groundBtn').addEventListener('click', () => startTimer({ kicker: 'GROUNDING GUIDE', title: 'Use your five senses', text: 'Look around and slowly name the things you can see, feel, hear, smell, and taste.', seconds: 60 }));
  byId('pulseBtn').addEventListener('click', () => showModal('Your wellness pulse', 'This indicator reflects check-ins stored on this device. It is not a diagnosis.')); byId('journeyBtn').addEventListener('click', () => showModal('Your gentle progress', `You have ${history.length} saved check-ins on this device. Small steps count.`, 'YOUR JOURNEY'));
  byId('consentBtn').addEventListener('click', () => showModal('You stay in control', '<div class="consent-flow"><div><strong>You choose</strong><span>check-in and sharing preferences</span></div><b>→</b><div><strong>MindCare</strong><span>stores this demo locally on this device</span></div><b>→</b><div><strong>Counselor</strong><span>only sees consented support signals</span></div></div><p class="modal-note">Emergency support remains human-led and follows local protocol. This prototype does not send information to a server.</p>', 'YOUR CHOICES', 'Review later', true));
  document.querySelector('.profile').addEventListener('click', () => { byId('roleGate').hidden = false; byId('appShell').hidden = true; }); document.querySelector('.chat-card .more').addEventListener('click', () => showModal('About Rio', 'Rio is a transparent, rule-based demo guide. It is not an NLU model, therapist, or emergency service.', 'CHAT INFORMATION', 'Close')); document.querySelector('.resource-card .more').addEventListener('click', () => showModal('More support tools', 'This demo keeps options simple. A production version can include saved resources and accessibility preferences.', 'MORE OPTIONS', 'Close'));
  byId('openChatBtn').addEventListener('click', () => { openView('care'); byId('chatText').focus(); }); byId('checkinBtn').addEventListener('click', () => showModal('Gentle check-in sent', `${currentPerson().name} will receive a kind invitation to share how things are going.`, 'COUNSELOR ACTION', 'Close'));
  byId('refreshBtn').addEventListener('click', (event) => { const person = people.find((entry) => entry.id === 'yaswant'); person.score = person.score >= 74 ? 58 : 74; person.status = person.score >= 70 ? 'Review' : 'Watch'; person.tone = person.score >= 70 ? 'review' : 'watch'; person.queueMeta = person.score >= 70 ? 'Trial · Missed two check-ins' : 'Trial · Checked in just now'; person.signal = person.score >= 70 ? 'A follow-up may be helpful after missed check-ins.' : 'New check-in received; continue to observe the pattern.'; person.preview = person.score >= 70 ? '“I have missed a couple of check-ins this week.”' : '“I checked in today and feel a little more settled.”'; selectedPersonId = person.id; save(); renderCaseList(); renderCounselorDetail(person); event.currentTarget.textContent = '✓ New demo signal received'; window.setTimeout(() => { event.currentTarget.textContent = '↻ Refresh overview'; }, 1800); });
  document.querySelector('.filter').addEventListener('click', (event) => { const showAll = event.currentTarget.dataset.reviewOnly === 'true'; event.currentTarget.dataset.reviewOnly = String(!showAll); event.currentTarget.textContent = showAll ? 'Filter ⌄' : 'Showing review only'; byId('caseList').querySelectorAll('.case-row').forEach((row) => { row.hidden = !showAll && !row.querySelector('.review'); }); }); document.querySelectorAll('.nav-link').forEach((button) => button.addEventListener('click', () => openView(button.dataset.view))); byId('language').addEventListener('change', applyLanguage); document.addEventListener('click', (event) => { if (event.target.closest('[data-close-modal]') || event.target === byId('modal')) stopTimer(false); });
  const redraw = () => { setMood(selectedMoodName, undefined, false); renderJourney(); renderCaseList(); renderCounselorDetail(currentPerson()); applyLanguage(); };
  const loadDatabaseState = async () => {
    if (!location.protocol.startsWith('http')) return;
    try {
      const response = await window.fetch('/api/state');
      const state = response.ok ? await response.json() : {};
      if (Array.isArray(state.people) && state.people.length) {
        people.splice(0, people.length, ...state.people);
        selectedMoodName = moodData[state.selectedMoodName] ? state.selectedMoodName : 'Okay';
        selectedPersonId = state.selectedPersonId || 'akshavi';
        history = Array.isArray(state.history) && state.history.length ? state.history : history;
      }
    } catch { /* Running without the local server is supported. */ }
    databaseHydrated = true;
    redraw();
    save();
  };
  redraw();
  loadDatabaseState();
})();
